id: P0DFF25C5
initial_creation_type: input
source_metadata:
  title: Aśvaghoṣa Series
  language: bo
  description: 'Texts by and about the great Indian master Aśvaghoṣa (Tib. rta dbyangs):'
  volume:
    0bdbf4a437c74a79ac8c0f824e68b598:
      title: Extremely Concise Dedication
      parent: Dedication
    9be22f3ab5994904bff77b7ead67af6e:
      title: Root Downfalls of the Vajra Vehicle
      parent: Samaya
    f15d996a329e4c2dbb31d778eada31f7:
      title: Summary of the Root Downfalls of the Vajra Vehicle
      parent: Samaya
created_at: '2022-03-01T02:09:56.156867'
last_modified_at: '2022-03-01T02:09:56.156870'
statistics:
  total_words: 1011
  total_non_words: 116
quality:
  non_words_ratio: 0.11
